@echo off
echo Starting Mental Health Support App...
echo.
echo Starting API server on port 3001...
start /B node server.js
echo.
echo Waiting for API server to start...
timeout /t 3 /nobreak >nul
echo.
echo Starting React app on port 3000...
npm start